---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(getLattes)
```

```{r}
lattes <- xml2::read_xml("6929645347412345.zip")
```

```{r}

dados <- getDadosGerais(lattes)

obterdadoslattes <- function(lattes){ 
  dados <- list(data.frame(getDadosGerais(lattes)),
data.frame(getArtigosPublicados(lattes)),
data.frame(getAtuacoesProfissionais(lattes)),
data.frame(getBancasDoutorado(lattes)),
data.frame(getBancasGraduacao(lattes)),
data.frame(getBancasMestrado(lattes)),
data.frame(getCapitulosLivros(lattes)),
data.frame(getDadosGerais(lattes)),
data.frame(getEnderecoProfissional(lattes)),
data.frame(getEventosCongressos(lattes)),
data.frame(getFormacaoDoutorado(lattes)),
data.frame(getFormacaoMestrado(lattes)),
data.frame(getFormacaoGraduacao(lattes)),
data.frame(getIdiomas(lattes)),
data.frame(getLinhaPesquisa(lattes)),
data.frame(getLivrosPublicados(lattes)),
data.frame(getOrganizacaoEventos(lattes)),
data.frame(getOrientacoesDoutorado(lattes)),
data.frame(getOrientacoesMestrado(lattes)),
data.frame(getOrientacoesPosDoutorado(lattes)),
data.frame(getOutrasProducoesTecnicas(lattes)),
data.frame(getParticipacaoProjeto(lattes)),
data.frame(getProducaoTecnica(lattes)),
data.frame(getId(lattes)))
  }

obterdadoslattes(lattes)

```

```{r}
artigos <- getArtigosPublicados(lattes)
livros <- getCapitulosLivros(lattes)
congressos <- getLattes::getTrabalhosEmEventos(lattes)
projetos<- getParticipacaoProjeto(lattes)
```

```{r}
library(tidyverse)
```

```{r}
projetos %>% 
  filter(ano_inicio>2020) %>% 
  select(nome_do_projeto_ingles, ano_inicio,financiadores) %>% 
  knitr::kable()
```
